# DEPLOYMENT ENVIRONMENT
# production | staging
ENVIRONMENT=production

# TARGET_ARCH
# amd64 | arm64 | multi
TARGET_ARCH=arm64

# DOCKER
IMAGE_NAME="archi-designer"

# COOLIFY
# application | service
DEPLOYMENT_TYPE=application 
COOLIFY_STAGING_UUID=
COOLIFY_PROD_UUID=x888w4gc8ckcsskoocsc0oc8

# DEBUG
# true  = show all docker / ssh / curl output
# false = clean output (default)
DEBUG=false

# CLEANUP
# Set to false if this project wants cleanup enabled
# true (default) | false
SKIP_CLEANUP=false
